version: "3.3"

services:
    db:
        container_name: info_db
        image: mysql
        restart: unless-stopped

        environment:
            - MYSQL_DATABASE=sharetrip
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - 3030:3306
        volumes:
            - db:/var/lib/mysql

    app:
        container_name: info_app
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - db
        env_file: ./.env
        environment:
            - DB_HOST=db
            - DB_USER=root
            - DB_PASSWORD=123456
        ports:
            - 3000:3000
        volumes:
            - ./:/app

volumes:
    db:
