version: "3.3"

services:
    db:
        container_name: info_db
        image: mysql
        restart: unless-stopped

        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - 3030:3306
        volumes:
            - db:/var/lib/mysql

    app:
        container_name: info_app
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - db
        env_file: ./.env
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/app

volumes:
    db:
