name: CI

on:
    push:
        branches:
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    load-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm install

            - name: Run Artillery load test
              run: npm run test:load
